### ISSUE TITLE
PLV8 JavaScript Extensions

### ISSUE THREAD

**Issue by bchavez** [mihasic/PostgreSql.Binaries.Lite#1]
Thanks for creating this package. It makes development with PostgreSQL much easier w/ a scripted build system. I wish the official PostgreSQL distribution was like this (without all the extra junk).

I'm using [**Marten**](https://github.com/jasperfx/marten) and one of the dependencies is the PLV8 JavaScript extension.

* Could you [include](http://www.postgresonline.com/journal/archives/367-PLV8-binaries-for-PostgreSQL-9.6-windows-both-32-bit-and-64-bit.html) the [PLV8 extension](https://pgxn.org/dist/plv8/doc/plv8.html) with your NuGet package?
* Or maybe would it be best to create a `PostgreSql.Binaries.Plv8` package?

Thanks for your consideration.

:tropical_drink: :wine_glass: ***["Some people drink Pepsi... Some people drink Coke..."](https://www.youtube.com/watch?v=p99a6K81zqM)***

**Comment by mihasic** [comment]
Thank you for the feedback.
The issue I'm having with Plv8 is - it's not officially supported on windows and does not seem to be maintained much (beta1 since a year ago), while the nuget package is for windows 64-bit only.

I'll give it a look later this week, though cannot promise maintaining it much.
If happens, will definitely be a separate package.

**Comment by mihasic** [comment]
@bchavez , you can try the nuget package PostgreSql.Binaries.Lite.Plv8. Haven't tried it personally. It's the same as original one (non plv8), but with the files from [PostgreSQL 9.6beta1 plv8 64-bit download - PL/V8 1.4.8](http://www.postgresonline.com/journal/archives/367-PLV8-binaries-for-PostgreSQL-9.6-windows-both-32-bit-and-64-bit.html)

**Comment by bchavez** [comment]
Hi @mihasic , thanks a bunch! Working great so far!

Was expecting only the PVL8 binaries, but I see the NuGet PVL8 package already includes PostgreSQL! Thanks a bunch! Makes my build script much easier!

Thanks again for your help!
Brian
